name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: brodrigu/github-pages-deploy-action@dev
      env:
        ACCESS_TOKEN: ${{ secrets.DEPLOY_KEY }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: dist # The folder the action should deploy.
        BUILD_SCRIPT: npm install && npm run dist # The build script the action should run prior to deploying.
        CNAME: bradandadrianne.com
